### ISSUE TITLE
Known issues

### ISSUE THREAD

**Issue by Tfarcenim** [Tfarcenim/ClassicBar#1]
it doesn't seem to work with nutrition. The entire health bar it usually shows was shifted up about 4-5 rows, as if there were invisible rows below it. Although that might be the interaction with several mods

Works in dev environment and small pack, why does it break with e2e?

Resolved -Advanced Rocketry oxygen bar ends up over the armor toughness bar. change the advanced rocketry config up by 10 if toughness bar is enabled

**Comment by Tfarcenim** [comment]
If you have any further issues to report, make a new ticket.

**Comment by Nazta** [comment]
It's probably not Nutrition, since it just adds buffs. [Spice of Life: Carrot Edition](https://minecraft.curseforge.com/projects/spice-of-life-carrot-edition) adds the hearts, so it might be that. 

But after some quick testing([modlist](https://pastebin.com/VZsmWkdv)), it doesn't seem like it's the culprit either. I'm currently at more health than the [screenshot on reddit](https://i.imgur.com/cEG42Hq.png) and it's [showing up fine](https://i.imgur.com/UPYS5qA.png).

I'm going to guess it's some interaction with different mods wanting to display health/armor values.

**Comment by captcookie** [comment]
wrong, nutrition does add hearts and buffs

**Comment by Nazta** [comment]
Nutrition adds temporary hearts through the toughness buff, but SoL Carrot edition adds permanent hearts based on how many different foods you've eaten.

**Comment by Tfarcenim** [comment]
I've added some code as of 0.0.7 to protect against mantle overriding the healthbar and I'll look into other mods that do the same thing.

**Comment by captcookie** [comment]
Like I said, the hearts are permanent unless you over time drop in nutrition. It works exactly like SoL based on the foods you've eaten. Therefore, you can maintain a second row of hearts for an infinite amount of time as long as you eat a variety of diet just like sol.

**Comment by Tfarcenim** [comment]
It was rustic breaking the armor bar, but it thankfully has a config to disable it.

**Comment by MokahTGS** [comment]
I'm having an issue with the hunger bar not showing (just showing as vanilla) and I've got SoL Carrot Ed but not Nutrition.  Not sure if this is part of this issue or if I should make a separate ticket.

**Comment by MokahTGS** [comment]
OK, this is beyond frustrating.  I can't get the hunger bar to use the CB one no matter what I do.  I know it works with Nutrition because the ATM3 Remix mod pack has it and Nutrition.

Anyone see any conflicting mods?

My mod list: https://pastebin.com/J4mGb433

**Comment by Curunir** [comment]
+1 for Nutrition being blameless. I have Nutrition in my pack, and it works just right.

**Comment by Tfarcenim** [comment]
no reason for this to be around anymore
