### ISSUE TITLE
Better Diving incompatibility.

### ISSUE THREAD

**Issue by ZapikCZ** [Tfarcenim/ClassicBar#15]
[Better Diving](https://minecraft.curseforge.com/projects/better-diving) changes the way air works, causing ian incompatibility with your mod.

I have no ideas about how to work with it, since the mod also adds its own air bar as a circle left of the hotbar.

So, just bringing it to your attention.

**Comment by Tfarcenim** [comment]
This is a tricky one as the mod isn't open source so I have to figure out how it does it's own air thing.

It's possible to disable the oxygen hud, but idk if the vanilla oxygen bar would even display correct.

**Comment by Curunir** [comment]
I'll +1 that request. Better Diving is a pretty interesting mod, and having it integrate with ClassicBars would be very nice. Agreed on the low priority, though, since BetterDiving can work with its circle HUD for the time being.

**Comment by Curunir** [comment]
I wonder if you even have to do much here. Tested this just now with the latest versions of ClassicBars and BetterDiving, and
1. the oxygen bars displays fine
2. diving time is not quite correct apparently, since I started suffocating when the bar was down, although the Better Diving circle had three seconds left.
![classic_bars_betterdiving](https://user-images.githubusercontent.com/8467967/64861498-656e1c00-d630-11e9-95d1-2a6ccc9a2b75.png)

So I'll say this is alright for now. Probably best to reach out to meldexun and see what could be done to optimise.
https://www.curseforge.com/minecraft/mc-mods/better-diving
